site_name: GAMEFUSE
site_url:

nav:
  - Game Engine Libraries: 
      - index.md
      
      - C# Unity 3D:
        - C# Unity 3D/getting started.md
        - Game Connection and Variables (C#): C# Unity 3D/game connection and variables.md
        - Signing Game Users Up (C#): C# Unity 3D/signing game users up.md
        - Creating Store Items on the Web (C#): C# Unity 3D/creating store items on the web.md
        - Using Store Items in Your Game (C#): C# Unity 3D/using the store in your game.md
        - Using Credits (C#): C# Unity 3D/using credits.md
        - Custom User Data (C#): C# Unity 3D/custom user data.md
        - In Game Leaderboard (C#): C# Unity 3D/in game leaderboard.md
        - Forgot Password (C#): C# Unity 3D/forgot password.md
        - Friends (C#): C# Unity 3D/friends.md
        - Groups (C#): C# Unity 3D/groups.md
        - Game Rounds (C#): C# Unity 3D/game rounds.md
        - Chat (C#): C# Unity 3D/chat.md
        - Class Methods (C#): C# Unity 3D/class methods.md
      - Blueprints Unreal: 
        - V2.9 Update [Breaking Changes] (BP): C++ Unreal Engine/V2.9 Update Changelist.md
        - V2.9 Migration Guide (BP): Blueprints Unreal/V2.9 Blueprint Migration Guide.md
        - Getting Started (BP): Blueprints Unreal/getting started.md
        - Game Connection and Variables (BP): Blueprints Unreal/game connection and variables.md
        - Signing Game Users Up (BP): Blueprints Unreal/signing game users up.md
        - Signing Game Users In (BP): Blueprints Unreal/signing game users in.md
        - Creating Store Items on the Web (BP): Blueprints Unreal/creating store items on the web.md
        - Using Store Items in Your Game (BP): Blueprints Unreal/using the store in your game.md
        - Using Credits (BP): Blueprints Unreal/using credits.md
        - Custom User Data (BP): Blueprints Unreal/custom user data.md
        - In Game Leaderboard (BP): Blueprints Unreal/in game leaderboard.md
        - Forgot Password (BP): Blueprints Unreal/forgot password.md
        - Friends (BP): Blueprints Unreal/friends.md
        - Groups (BP): Blueprints Unreal/groups.md
        - Rounds (BP): Blueprints Unreal/rounds.md
        - Chat (BP): Blueprints Unreal/chat.md
        - Class Methods (BP): Blueprints Unreal/class methods.md
        - Struct Reference (BP): C++ Unreal Engine/struct reference.md
      - C++ Unreal Engine: 
        - v2.9 Update [Breaking Changes] (C++): C++ Unreal Engine/V2.9 Update Changelist.md
        - v2.9 Migration Guide (C++): C++ Unreal Engine/V2.9 Unreal C++ Migration Guide.md
        - Getting Started (C++): C++ Unreal Engine/getting started.md
        - Game Connection and Variables (C++): C++ Unreal Engine/game connection and variables.md
        - Signing Game Users Up (C++): C++ Unreal Engine/signing game users up.md
        - Signing Game Users In (C++): C++ Unreal Engine/signing game users in.md
        - Creating Store Items on the Web (C++): C++ Unreal Engine/creating store items on the web.md
        - Using Store Items in Your Game (C++): C++ Unreal Engine/using the store in your game.md
        - Using Credits (C++): C++ Unreal Engine/using credits.md
        - Custom User Data (C++): C++ Unreal Engine/custom user data.md
        - In Game Leaderboard (C++): C++ Unreal Engine/in game leaderboard.md
        - Forgot Password (C++): C++ Unreal Engine/forgot password.md
        - Friends (C++): C++ Unreal Engine/friends.md
        - Groups (C++): C++ Unreal Engine/groups.md
        - Rounds (C++): C++ Unreal Engine/rounds.md
        - Chat (C++): C++ Unreal Engine/chat.md
        - Class Methods (C++): C++ Unreal Engine/class methods.md
        - Struct Reference (C++): C++ Unreal Engine/struct reference.md
        - Callback Reference (C++): C++ Unreal Engine/callback reference.md 
      - JS Playcanvas, PixiJS, BabylonJS :
        - JS Playcanvas, PixiJS, BabylonJS/getting started.md
        - Game Connection and Variables (JS): JS Playcanvas, PixiJS, BabylonJS/game connection and variables.md
        - Signing Game Users Up (JS): JS Playcanvas, PixiJS, BabylonJS/signing game users up.md
        - Signing Game Users In (JS): JS Playcanvas, PixiJS, BabylonJS/signing game users in.md
        - Creating Store Items on the Web (JS): JS Playcanvas, PixiJS, BabylonJS/creating store items on the web.md
        - Using Store Items in Your Game (JS): JS Playcanvas, PixiJS, BabylonJS/using the store in your game.md
        - Using Credits (JS): JS Playcanvas, PixiJS, BabylonJS/using credits.md
        - Custom User Data (JS): JS Playcanvas, PixiJS, BabylonJS/custom user data.md
        - In Game Leaderboard (JS): JS Playcanvas, PixiJS, BabylonJS/in game leaderboard.md
        - Forgot Password (JS): JS Playcanvas, PixiJS, BabylonJS/forgot password.md
        - Class Methods (JS): JS Playcanvas, PixiJS, BabylonJS/class methods.md
        - Friends (JS): 'JS Playcanvas, PixiJS, BabylonJS/friends.md'
      - API Full REST API:
        - API Full REST API/getting started.md
        - Game Connection and Variables (API): API Full REST API/game connection and variables.md
        - Signing Game Users Up (API): API Full REST API/signing game users up.md
        - Signing Game Users In (API): API Full REST API/signing game users in.md
        - Accessing User Data (API): API Full REST API/other users.md
        - Creating Store Items on the Web (API): API Full REST API/creating store items on the web.md
        - Using Store Items in Your Game (API): API Full REST API/using the store in your game.md
        - Using Credits (API): API Full REST API/using credits.md
        - Custom User Data (API): API Full REST API/custom user data.md
        - Friends (API): API Full REST API/friends.md
        - Groups (API): API Full REST API/groups.md
        - Messaging (API): API Full REST API/messaging.md
        - Game Rounds (API): API Full REST API/game rounds.md
        - In Game Leaderboard (API): API Full REST API/in game leaderboard.md
        - Forgot Password (API): API Full REST API/forgot password.md
        - Class Methods (API): API Full REST API/class methods.md
      - Miscellaneous:
        - Forgot Password: generic/forgot_password.md
        - Creating Store Items on the Web: generic/creating_store_items_on_the_web.md
        - Service Key Access: generic/service_key_access.md
        # - Cloud Code: generic/cloud_code.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
  font:
    text: Chakra Petch 300
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange
    


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - toc:
        permalink: true
        toc_depth: 2
    - tables
    - attr_list
    - pymdownx.emoji
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details

plugins:
  - search
  - section-index

extra_css:
  - custom.css
