site_name: GameFuse Docs
site_url:

nav:
  - Plugin: 
      - index.md
      - C# Unity 3D:
        - C# Unity 3D/getting started.md
        - Game Connection and Variables: C# Unity 3D/game connection and variables.md
        - Signing game users up: C# Unity 3D/signing game users up.md
        - Creating store items on the web: C# Unity 3D/creating store items on the web.md
        - Using the store in your game: C# Unity 3D/using the store in your game.md
        - Using Credits: C# Unity 3D/using credits.md
        - Custom user data: C# Unity 3D/custom user data.md
        - In game leaderboard: C# Unity 3D/in game leaderboard.md
        - Forgot Password: C# Unity 3D/forgot password.md
        - Class Methods: C# Unity 3D/class methods.md
      - Blueprints Unreal: 
        - Blueprints Unreal/getting started.md
        - Game Connection and Variables: Blueprints Unreal/game connection and variables.md
        - Signing game users up: Blueprints Unreal/signing game users up.md
        - Signing game users in: Blueprints Unreal/signing game users in.md
        - Creating store items on the web: Blueprints Unreal/creating store items on the web.md
        - Using the store in your game: Blueprints Unreal/using the store in your game.md
        - Using Credits: Blueprints Unreal/using credits.md
        - Custom user data: Blueprints Unreal/custom user data.md
        - In game leaderboard: Blueprints Unreal/in game leaderboard.md
        - Forgot Password: Blueprints Unreal/forgot password.md
        - Class Methods: Blueprints Unreal/class methods.md
      - C++ Unreal Engine: 
        - C++ Unreal Engine/getting started.md
        - Game Connection and Variables: C++ Unreal Engine/game connection and variables.md
        - Signing game users up: C++ Unreal Engine/signing game users up.md
        - Signing game users in: C++ Unreal Engine/signing game users in.md
        - Creating store items on the web: C++ Unreal Engine/creating store items on the web.md
        - Using the store in your game: C++ Unreal Engine/using the store in your game.md
        - Using Credits: C++ Unreal Engine/using credits.md
        - Custom user data: C++ Unreal Engine/custom user data.md
        - In game leaderboard: C++ Unreal Engine/in game leaderboard.md
        - Forgot Password: C++ Unreal Engine/forgot password.md
        - Class Methods: C++ Unreal Engine/class methods.md
      - JS Playcanvas, PixiJS, BabylonJS:
        - JS Playcanvas, PixiJS, BabylonJS/getting started.md
        - Game Connection and Variables: JS Playcanvas, PixiJS, BabylonJS/game connection and variables.md
        - Signing game users up: JS Playcanvas, PixiJS, BabylonJS/signing game users up.md
        - Signing game users in: JS Playcanvas, PixiJS, BabylonJS/signing game users in.md
        - Creating store items on the web: JS Playcanvas, PixiJS, BabylonJS/creating store items on the web.md
        - Using the store in your game: JS Playcanvas, PixiJS, BabylonJS/using the store in your game.md
        - Using Credits: JS Playcanvas, PixiJS, BabylonJS/using credits.md
        - Custom user data: JS Playcanvas, PixiJS, BabylonJS/custom user data.md
        - In game leaderboard: JS Playcanvas, PixiJS, BabylonJS/in game leaderboard.md
        - Forgot Password: JS Playcanvas, PixiJS, BabylonJS/forgot password.md
        - Class Methods: JS Playcanvas, PixiJS, BabylonJS/class methods.md
  - API Full REST API:
      - API Full REST API/getting started.md
      - Game Connection and Variables: API Full REST API/game connection and variables.md
      - Signing game users up: API Full REST API/signing game users up.md
      - Signing game users in: API Full REST API/signing game users in.md
      - Creating store items on the web: API Full REST API/creating store items on the web.md
      - Using the store in your game: API Full REST API/using the store in your game.md
      - Using Credits: API Full REST API/using credits.md
      - Custom user data: API Full REST API/custom user data.md
      - In game leaderboard: API Full REST API/in game leaderboard.md
      - Forgot Password: API Full REST API/forgot password.md
      - Class Methods: API Full REST API/class methods.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
  font:
    text: Chakra Petch 300
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange
    


markdown_extensions:
    - toc:
        permalink: true
    - tables
    - attr_list
    - pymdownx.emoji
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

plugins:
  - search
  - section-index

extra_css:
  - custom.css