site_name: GAMEFUSE
site_url:

nav:
  - Game Engine Libraries: 
      - index.md
      
      - C# Unity 3D:
        - C# Unity 3D/getting started.md
        - GameFuse Settings Configuration (C#): C# Unity 3D/gamefuse settings configuration.md
        - Signing Game Users Up (C#): C# Unity 3D/signing game users up.md
        - Creating Store Items on the Web (C#): C# Unity 3D/creating store items on the web.md
        - Using Store Items in Your Game (C#): C# Unity 3D/using the store in your game.md
        - Using Credits (C#): C# Unity 3D/using credits.md
        - Custom User Data (C#): C# Unity 3D/custom user data.md
        - In Game Leaderboard (C#): C# Unity 3D/in game leaderboard.md
        - Forgot Password (C#): C# Unity 3D/forgot password.md
        - Friends (C#): C# Unity 3D/friends.md
        - Groups (C#): C# Unity 3D/groups.md
        - Game Rounds (C#): C# Unity 3D/game rounds.md
        - Chat (C#): C# Unity 3D/chat.md
        - Class Methods (C#): C# Unity 3D/class methods.md
      - Blueprints Unreal: 
        - Getting Started: Blueprints Unreal/getting started.md
        - Game Connection and Variables: Blueprints Unreal/game connection and variables.md
        - GameFuseUser:
          - Signing game users up: Blueprints Unreal/signing game users up.md
          - Signing game users in: Blueprints Unreal/signing game users in.md
          - Creating store items on the web: Blueprints Unreal/creating store items on the web.md
          - Using the store in your game: Blueprints Unreal/using the store in your game.md
          - Using Credits: Blueprints Unreal/using credits.md
          - Custom user data: Blueprints Unreal/custom user data.md
          - In game leaderboard: Blueprints Unreal/in game leaderboard.md
          - Forgot Password: Blueprints Unreal/forgot password.md
        - Friends: Blueprints Unreal/friends.md
        - Groups: Blueprints Unreal/groups.md
        - Rounds: Blueprints Unreal/rounds.md
        - Chat: Blueprints Unreal/chat.md
        - Class Methods: Blueprints Unreal/class methods.md
        - Struct Reference: C++ Unreal Engine/struct reference.md
        - Callback Reference: Blueprints Unreal/callback reference.md
        - <V2.9 Migration Guide:
          - V2.9 Update [Breaking Changes]: C++ Unreal Engine/V2.9 Update Changelist.md
          - V2.9 Migration Guide: Blueprints Unreal/V2.9 Blueprint Migration Guide.md
      - C++ Unreal Engine: 
        - Getting Started: C++ Unreal Engine/getting started.md
        - Game Connection and Variables: C++ Unreal Engine/game connection and variables.md
        - GameFuseUser:
          - Signing game users up: C++ Unreal Engine/signing game users up.md
          - Signing game users in: C++ Unreal Engine/signing game users in.md
          - Creating store items on the web: C++ Unreal Engine/creating store items on the web.md
          - Using the store in your game: C++ Unreal Engine/using the store in your game.md
          - Using Credits: C++ Unreal Engine/using credits.md
          - Custom user data: C++ Unreal Engine/custom user data.md
          - In game leaderboard: C++ Unreal Engine/in game leaderboard.md
          - Forgot Password: C++ Unreal Engine/forgot password.md
        - Friends: C++ Unreal Engine/friends.md
        - Groups: C++ Unreal Engine/groups.md
        - Rounds: C++ Unreal Engine/rounds.md
        - Chat: C++ Unreal Engine/chat.md
        - Class Methods: C++ Unreal Engine/class methods.md
        - Struct Reference: C++ Unreal Engine/struct reference.md
        - Callback Reference: C++ Unreal Engine/callback reference.md 
        - <V2.9 Migration Guide:
          - v2.9 Update [Breaking Changes]: C++ Unreal Engine/V2.9 Update Changelist.md
          - v2.9 Migration Guide: C++ Unreal Engine/V2.9 Unreal C++ Migration Guide.md
      - JS Playcanvas, PixiJS, BabylonJS:
        - JS Playcanvas, PixiJS, BabylonJS/getting started.md
        - Game Connection and Variables (JS): JS Playcanvas, PixiJS, BabylonJS/game connection and variables.md
        - Signing Game Users Up (JS): JS Playcanvas, PixiJS, BabylonJS/signing game users up.md
        - Signing Game Users In (JS): JS Playcanvas, PixiJS, BabylonJS/signing game users in.md
        - Creating Store Items on the Web (JS): JS Playcanvas, PixiJS, BabylonJS/creating store items on the web.md
        - Using Store Items in Your Game (JS): JS Playcanvas, PixiJS, BabylonJS/using the store in your game.md
        - Using Credits (JS): JS Playcanvas, PixiJS, BabylonJS/using credits.md
        - Custom User Data (JS): JS Playcanvas, PixiJS, BabylonJS/custom user data.md
        - In Game Leaderboard (JS): JS Playcanvas, PixiJS, BabylonJS/in game leaderboard.md
        - Forgot Password (JS): JS Playcanvas, PixiJS, BabylonJS/forgot password.md
        - Class Methods (JS): JS Playcanvas, PixiJS, BabylonJS/class methods.md
        - Friends (JS): 'JS Playcanvas, PixiJS, BabylonJS/friends.md'
      - API Full REST API:
        - API Full REST API/getting started.md
        - Game Connection and Variables (API): API Full REST API/game connection and variables.md
        - Signing Game Users Up (API): API Full REST API/signing game users up.md
        - Signing Game Users In (API): API Full REST API/signing game users in.md
        - Accessing User Data (API): API Full REST API/other users.md
        - Creating Store Items on the Web (API): API Full REST API/creating store items on the web.md
        - Using Store Items in Your Game (API): API Full REST API/using the store in your game.md
        - Using Credits (API): API Full REST API/using credits.md
        - Custom User Data (API): API Full REST API/custom user data.md
        - Friends (API): API Full REST API/friends.md
        - Groups (API): API Full REST API/groups.md
        - Messaging (API): API Full REST API/messaging.md
        - Game Rounds (API): API Full REST API/game rounds.md
        - In Game Leaderboard (API): API Full REST API/in game leaderboard.md
        - Forgot Password (API): API Full REST API/forgot password.md
        - Class Methods (API): API Full REST API/class methods.md
      - Miscellaneous:
        - Forgot Password: generic/forgot_password.md
        - Creating Store Items on the Web: generic/creating_store_items_on_the_web.md
        - Service Key Access: generic/service_key_access.md
        # - Cloud Code: generic/cloud_code.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
  font:
    text: Chakra Petch 300
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange
    


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - toc:
        permalink: true
        toc_depth: 2
    - tables
    - attr_list
    - pymdownx.emoji
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details

plugins:
  - search
  - section-index

extra_css:
  - custom.css
